import { useQuery } from '@tanstack/react-query'
import { ClockIcon } from '@heroicons/react/24/outline'
import { studentsAPI } from '../services/api'
import { formatCurrency, formatDateTime, formatTransactionType } from '../utils/format'
import StudentPaymentPlan from './StudentPaymentPlan'

export default function StudentDetails({ student, onChanged, children }) {
  const { data: historyResponse, isLoading } = useQuery({ queryKey: ['student-details-history', student.id], queryFn: () => studentsAPI.getHistory(student.id) })
  const history = historyResponse?.results || historyResponse || []
  const finance = student.financial_summary || {}
  return <section className="card p-6"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-100 pb-4"><div><h2 className="text-xl font-extrabold text-slate-900">{student.full_name}</h2><p className="mt-1 text-sm text-slate-500">{student.phone || 'Телефон не указан'} · {student.group_name}</p><p className="mt-1 text-sm text-slate-500">Ассистент: {student.assistant_name || '—'} · Договор: {student.contract_status || 'unknown'}</p>{student.comment && <p className="mt-1 text-sm text-slate-500">{student.comment}</p>}</div>{children}</div><div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Metric label="Цена курса" value={student.course_price ? formatCurrency(student.course_price) : '—'} /><Metric label="Оплачено" value={formatCurrency(finance.total_paid || student.amount_paid_total || 0)} /><Metric label="Сегодня" value={formatCurrency(finance.due_now || 0)} /><Metric label="Просрочено" value={formatCurrency(finance.overdue_amount || 0)} /><Metric label="Остаток" value={finance.contract_remaining === null ? '—' : formatCurrency(finance.contract_remaining || 0)} /><Metric label="Переплата" value={formatCurrency(finance.credit_amount || 0)} /></div><p className="mt-3 text-sm text-slate-600">Обучение: {student.learning_status} · {student.group_technology || 'Направление не указано'} · следующий платёж: {finance.next_payment_date || '—'} {finance.next_payment_amount && formatCurrency(finance.next_payment_amount)}</p><StudentPaymentPlan student={student} onChanged={onChanged} /><div className="mt-6"><h3 className="mb-3 flex items-center gap-2 font-bold text-slate-900"><ClockIcon className="h-5 w-5" /> История оплат</h3>{isLoading ? <p className="text-sm text-slate-500">Загрузка…</p> : history.length ? <div className="space-y-2">{history.map((item) => <div key={item.id} className="flex justify-between rounded-xl border border-slate-100 p-3"><span>{formatTransactionType(item.type)} · {formatDateTime(item.created_at)}</span><b className="text-emerald-700">+{formatCurrency(item.amount)}</b></div>)}</div> : <p className="text-sm text-slate-500">Оплат пока нет.</p>}</div></section>
}

function Metric({ label, value }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p></div> }
